from pydantic import BaseModel, Field
from typing import List, Dict, Any

class WeeklyReviewReport(BaseModel):
    """Schema for the analytical synthesis generated by the Weekly Reviewer."""
    progress_summary: str = Field(description="Objective summary of the week's execution.")
    blocker_analysis: str = Field(description="Identification of recurring patterns or obstacles.")
    recommended_adjustments: List[str] = Field(description="Concrete, actionable adjustments to the schedule or task breakdown.")

class WeeklyReviewer:
    """
    Mode 3: The Weekly Reviewer.
    Handles analytical computation to synthesize historical execution logs into actionable strategic adjustments.
    """
    def __init__(self, brain_client):
        self.brain = brain_client
        
        self.reviewer_prompt = (
            "You are Allison, an analytical execution reviewer. Analyze the user's weekly check-in logs and task completion data. Synthesize progress, identify recurring blockers, and suggest concrete plan adjustments. Maintain a highly objective, disciplined, and supportive tone. Do not shame the user. Focus strictly on strategic optimization."
        )

    def generate_review(self, goal_summary: str, checkin_logs: List[Dict[str, Any]], tasks_completed: int, tasks_total: int) -> WeeklyReviewReport:
        """
        Executes the analytical review based on aggregated weekly metrics.
        """
        # Formats the raw JSON logs into a clean, human-readable string for the LLM
        formatted_logs = "\n".join([
            f"- Date: {log.get('timestamp', 'Unknown')[:10]} | Notes: {log.get('notes', 'None')} | Blockers: {log.get('blockers', 'None')}"
            for log in checkin_logs
        ]) if checkin_logs else "No check-ins recorded this week."

        payload = (
            f"Goal Context: {goal_summary}\n"
            f"Weekly Task Completion: {tasks_completed}/{tasks_total}\n"
            f"Check-in Logs:\n{formatted_logs}\n"
        )
        
        response = self.brain.client.models.generate_content(
            model=self.brain.model_id,
            contents=payload,
            config={
                'system_instruction': self.reviewer_prompt,
                'response_mime_type': 'application/json',
                'response_schema': WeeklyReviewReport,
            }
        )
        return response.parsed